# Generated by Django 3.1.6 on 2021-02-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210207_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='odd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='prediction',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
