# Generated by Django 3.1.6 on 2021-02-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210208_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='datetime',
        ),
    ]
