# Generated by Django 3.1.6 on 2021-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_game_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
