# Generated by Django 3.1.6 on 2021-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_betslip_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='slug',
            field=models.SlugField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betslip',
            name='status',
            field=models.CharField(default='NR', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='NR', max_length=10),
        ),
    ]
