# Generated by Django 3.1.6 on 2021-02-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210209_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='bet_slip_code',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
