# Generated by Django 3.1.6 on 2021-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210210_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='bet_slip_code',
            field=models.CharField(default='l2hrjhp9t5uhfz1jqnog', max_length=21),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
