# Generated by Django 3.1.6 on 2021-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210210_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='stake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='bet_slip_code',
            field=models.CharField(default='', max_length=21),
        ),
    ]
