# Generated by Django 3.1.6 on 2021-02-11 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
