# Generated by Django 3.1.6 on 2021-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210212_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
