# Generated by Django 3.1.6 on 2021-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210213_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='bet_slip_code',
            field=models.CharField(default='1395x639zgv6t3qdyx55', max_length=21),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='slug',
            field=models.SlugField(default='kuv6vonldlepnrozbqjd'),
        ),
    ]
