# Generated by Django 3.1.6 on 2021-02-16 10:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210213_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='bet_slip_code',
            field=models.CharField(default=core.models.get_random_value, max_length=21),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='slug',
            field=models.SlugField(default=core.models.get_random_value),
        ),
    ]
